version: '3.8'

services:
  django_api:
    container_name: django_api
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: django_db
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env.dev

volumes:
  pgdata:
