# Generated by Django 4.2.4 on 2023-08-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_age_alter_person_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(default='Not provided', verbose_name='Bio'),
        ),
    ]
